{
    "Categories": "Qt;KDE;X-KDE-information;",
    "KPlugin": {
        "BugReportUrl": "https://bugs.kde.org/enter_bug.cgi?product=kinfocenter&component=general",
        "Description": "PCI information",
        "Description[ar]": "معلومات PCI",
        "Description[az]": "PCİ məlumatı",
        "Description[bg]": "Данни за PCI шина",
        "Description[ca@valencia]": "Informació de PCI",
        "Description[ca]": "Informació de PCI",
        "Description[cs]": "Informace o PCI",
        "Description[de]": "Informationen zu PCI",
        "Description[en_GB]": "PCI information",
        "Description[eo]": "Informoj pri PCI",
        "Description[es]": "Información sobre PCI",
        "Description[et]": "PCI info",
        "Description[eu]": "PCIren informazioa",
        "Description[fi]": "PCI-tiedot",
        "Description[fr]": "Informations concernant l'interface PCI",
        "Description[gl]": "Información de PCI.",
        "Description[he]": "פרטי התקני PCI",
        "Description[hu]": "PCI-információk",
        "Description[ia]": "Information de PCI",
        "Description[id]": "Informasi PCI",
        "Description[is]": "Upplýsingar um PCI-braut",
        "Description[it]": "Informazioni sul bus PCI",
        "Description[ja]": "PCI の情報",
        "Description[ka]": "PCI მოწყობილობები",
        "Description[ko]": "PCI 정보",
        "Description[lt]": "Informacija apie PCI",
        "Description[nl]": "PCI-informatie",
        "Description[nn]": "PCI-informasjon",
        "Description[pa]": "PCI ਜਾਣਕਾਰੀ",
        "Description[pl]": "Szczegóły o PCI",
        "Description[pt]": "Informação sobre o PCI",
        "Description[pt_BR]": "Informações PCI",
        "Description[ro]": "Informații despre PCI",
        "Description[ru]": "Сведения об устройствах PCI",
        "Description[sk]": "Informácie o PCI",
        "Description[sl]": "Podatki o vodilu PCI",
        "Description[sv]": "Information om PCI",
        "Description[ta]": "PCI விவரங்கள்",
        "Description[tr]": "PCI Bilgisi",
        "Description[uk]": "Інформація щодо шини PCI",
        "Description[vi]": "Thông tin về PCI",
        "Description[x-test]": "xxPCI informationxx",
        "Description[zh_CN]": "PCI 信息",
        "Description[zh_TW]": "PCI 資訊",
        "Icon": "hwinfo",
        "Name": "PCI",
        "Name[af]": "PCI",
        "Name[ar]": "PCI",
        "Name[as]": "PCI",
        "Name[ast]": "PCI",
        "Name[az]": "PCI",
        "Name[be@latin]": "PCI",
        "Name[be]": "PCI",
        "Name[bg]": "PCI",
        "Name[bn]": "পি-সি-আই",
        "Name[bn_IN]": "PCI",
        "Name[br]": "PCI",
        "Name[bs]": "PCI",
        "Name[ca@valencia]": "PCI",
        "Name[ca]": "PCI",
        "Name[cs]": "PCI sběrnice",
        "Name[csb]": "PCI",
        "Name[cy]": "PCI",
        "Name[da]": "PCI",
        "Name[de]": "PCI",
        "Name[el]": "PCI",
        "Name[en_GB]": "PCI",
        "Name[eo]": "PCI",
        "Name[es]": "PCI",
        "Name[et]": "PCI",
        "Name[eu]": "PCI",
        "Name[fi]": "PCI",
        "Name[fr]": "PCI",
        "Name[fy]": "PCI",
        "Name[ga]": "PCI",
        "Name[gl]": "PCI",
        "Name[gu]": "PCI",
        "Name[he]": "התקני PCI",
        "Name[hi]": "पीसीआई",
        "Name[hne]": "पीसीआई",
        "Name[hr]": "PCI",
        "Name[hsb]": "PCI",
        "Name[hu]": "PCI",
        "Name[ia]": "PCI",
        "Name[id]": "PCI",
        "Name[is]": "PCI-braut",
        "Name[it]": "PCI",
        "Name[ja]": "PCI",
        "Name[ka]": "PCI",
        "Name[kk]": "PCI",
        "Name[km]": "PCI",
        "Name[kn]": "ಪಿಸಿಐ",
        "Name[ko]": "PCI",
        "Name[ku]": "PCI",
        "Name[lt]": "PCI",
        "Name[lv]": "PCI",
        "Name[mai]": "पीसीआई",
        "Name[mk]": "PCI",
        "Name[ml]": "പിസിഐ",
        "Name[mr]": "PCI",
        "Name[ms]": "PCI",
        "Name[nb]": "PCI",
        "Name[nds]": "PCI",
        "Name[ne]": "पीसीआई",
        "Name[nl]": "PCI",
        "Name[nn]": "PCI",
        "Name[oc]": "PCI",
        "Name[or]": "PCI",
        "Name[pa]": "PCI",
        "Name[pl]": "PCI",
        "Name[pt]": "PCI",
        "Name[pt_BR]": "PCI",
        "Name[ro]": "PCI",
        "Name[ru]": "PCI",
        "Name[se]": "PCI",
        "Name[si]": "PCI",
        "Name[sk]": "PCI",
        "Name[sl]": "PCI",
        "Name[sr@ijekavian]": "ПЦИ",
        "Name[sr@ijekavianlatin]": "PCI",
        "Name[sr@latin]": "PCI",
        "Name[sr]": "ПЦИ",
        "Name[sv]": "PCI",
        "Name[ta]": "PCI",
        "Name[te]": "పి సి ఐ",
        "Name[tg]": "PCI",
        "Name[th]": "อุปกรณ์ PCI",
        "Name[tr]": "PCI",
        "Name[ug]": "PCI",
        "Name[uk]": "Шина PCI",
        "Name[uz@cyrillic]": "PCI",
        "Name[uz]": "PCI",
        "Name[vi]": "PCI",
        "Name[wa]": "PCI",
        "Name[x-test]": "xxPCIxx",
        "Name[xh]": "PCI",
        "Name[zh_CN]": "PCI",
        "Name[zh_TW]": "PCI"
    },
    "TryExec": "@PCI_BACKEND@",
    "X-KDE-KInfoCenter-Category": "device_information",
    "X-KDE-Keywords": "PCI,PCI-Devices,PCI-Bus,System Information"
}
